### ISSUE TITLE
Why are Pearson loss and reg loss mutually exclusive? 

### ISSUE THREAD

**Issue by Master-cai** [ForMyCat/SparseGS#21]
Hiya! Thanks for your wonderful work! but i'm confused why are Pearson loss and reg loss mutually exclusive?  See
https://github.com/ForMyCat/SparseGS/blob/95e7aef29c5562400d3b2b38cc7e90436a432b7c/train.py#L149
and
https://github.com/ForMyCat/SparseGS/blob/95e7aef29c5562400d3b2b38cc7e90436a432b7c/train.py#L153

cc @ForMyCat

**Comment by ForMyCat** [comment]
Hi, thank you for you interest in our work.

Because we don't have GT images for warped views, hence no depth maps for pearson loss. I see your point is that we can run DPT model on the warped image (pseudo-GT) and apply pearson loss, but the result is heavily dependent on the warping quality. For RGB loss this is not too much of an issue since we can apply the warping mask. But DPT model cannot take in mask.
