### ISSUE TITLE
Depth loss

### ISSUE THREAD

**Issue by manurare** [ForMyCat/SparseGS#7]
Hi,

Thanks for sharing this amazing codebase!

I was wondering. Have you tried as depth loss a normal L1 loss. Do you have any insights of why it might or might not work compared with the pearson loss?

**Comment by ForMyCat** [comment]
The problem is that monocular estimation models only give you relative
depth maps, meaning the depth ranges from 0-1. A depth value of 1 from two
images may represent different metric depth values. If we simply normalize
all the rendered depth maps then do a L1 loss, the difference in variance
between views will cause ambiguity. We have not tested this yet, but a
possible approach is to use a MLP to find correct and consistent scalings
to scale all the relative depth maps to metric values, then fit a
pixel-wise loss such as L1/L2. I am curious about the result as well. Feel
free to follow up with me if you have some findings.
